site_name: marginaleffects for Python
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Functions API:
    - predictions: api/predictions.md
    - comparisons: api/comparisons.md
    - hypotheses: api/hypotheses.md

theme:
  name: "material"

markdown_extensions:
  - admonition
  - codehilite
  - mkautodoc
