[tool.poetry]
name = "marginaleffects"
version = "0.0.1"
description = ""
authors = ["Vincent Arel-Bundock <vincent.arel-bundock@umontreal.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pandas = "^2.0.2"
statsmodels = "^0.14.0"
numpy = "^1.25.0"
polars = "^0.18.3"
pyarrow = "^12.0.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
rpy2 = "^3.5.12"
jupyter = "^1.0.0"
mkdocs = "^1.4.3"
mkdocs-material = "^9.1.17"
mkautodoc = "^0.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
