name: Package Linting

on:
  workflow_dispatch:
  workflow_call:

jobs:
  linting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false

      - name: Install deps
        run: |
          poetry install --with=dev

      - name: Check isort formatting
        run: |
          poetry run isort marginaleffects --check

      - name: Check black formatting
        run: | 
          poetry run black marginaleffects --check

      - name: Check flake8
        run: | 
          poetry run flake8 marginaleffects