name: Package Linting

on:
  workflow_dispatch:
  workflow_call:

jobs:
  linting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v1

      - name: Install deps
        run: |
          rye sync

      - name: Check
        run: |
          rye run ruff check marginaleffects
          rye run ruff format marginaleffects --check
