name: Package Linting

on:
  workflow_dispatch:
  workflow_call:

jobs:
  linting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: false

      - name: Install deps
        run: |
          poetry install --with=dev

      - name: Check
        run: |
          poetry run ruff --check
          poetry run ruff format --check
